# Agent CLI Startup Script — graphtor-docs
#
# Sets workspace-local directories so that AI agent state (memories,
# checkpoints, database) is scoped to this workspace and git-visible.
#
# Activate the section matching your AI CLI tool.
# To switch tools, comment out the active section and uncomment another.
#
# Generated by autoharness. Re-run install or tune to regenerate.

# ── GitHub Copilot CLI ──────────────────────────────────────────────────────
# COPILOT_HOME redirects the Copilot CLI database and memory to a workspace-
# local directory. This keeps agent state visible in git and isolated per
# project rather than shared across all workspaces.
#
# This script does NOT install or refresh Auto-MergeInstall / Auto-Tune.
# Register those globally with `autoharness setup-copilot-cli`.
# Re-run that setup command after upgrading autoharness so updated agent and
# skill files are recopied into the standard Copilot CLI config directory.
#
# COPILOT_EXE_PATH must be an executable path only (no arguments).
# Set ai_tools.copilot_cli.exe_path in .autoharness/config.yaml if copilot
# is not on PATH, then re-run autoharness install or tune.
#

function Invoke-EngramCommandWithProgress {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Executable,

        [Parameter(Mandatory = $true)]
        [string]$Subcommand,

        [string[]]$GlobalArguments = @(),

        [string[]]$Arguments = @(),

        [Parameter(Mandatory = $true)]
        [string]$Activity,

        [Parameter(Mandatory = $true)]
        [string]$Status
    )

    Write-Host "$Activity — $Status"

    $engramArguments = @("--format", "text")
    $engramArguments += $GlobalArguments
    $engramArguments += $Subcommand
    $engramArguments += $Arguments

    & $Executable @engramArguments
    $exitCode = $LASTEXITCODE

    if ($exitCode -ne 0) {
        throw "engram $Subcommand failed with exit code $exitCode."
    }
}

$env:COPILOT_HOME = if ($env:COPILOT_HOME) { $env:COPILOT_HOME } else { Join-Path $PSScriptRoot ".copilot" }
$env:ENGRAM_DATA_DIR = if ($env:ENGRAM_DATA_DIR) { $env:ENGRAM_DATA_DIR } else { Join-Path $PSScriptRoot ".engram" }
if (-not $env:GITHUB_TOKEN) {
    $ghCmd = Get-Command gh -ErrorAction SilentlyContinue
    if ($ghCmd) {
        try {
            $ghToken = (& $ghCmd.Source auth token 2>$null).Trim()
            if ($ghToken) {
                $env:GITHUB_TOKEN = $ghToken
            }
        } catch {
            Write-Warning "gh auth token failed (non-fatal): $_"
        }
    }
}
$copilotExe = if ($env:COPILOT_EXE_PATH) {
    $env:COPILOT_EXE_PATH
} elseif ($env:COPILOT_EXE) {
    $env:COPILOT_EXE
} else {
    $copilotCommand = Get-Command "copilot" -ErrorAction SilentlyContinue
    if ($copilotCommand) { $copilotCommand.Source } else { $null }
}

if (-not $copilotExe) {
    throw "Unable to locate Copilot CLI. Set COPILOT_EXE_PATH (or COPILOT_EXE for backward compatibility) or add 'copilot' to PATH."
}

$backlogitCmd = Get-Command backlogit -ErrorAction SilentlyContinue
if ($backlogitCmd) {
    try {
        backlogit sync
    } catch {
        Write-Warning "backlogit sync failed (non-fatal): $_"
    }
}

$engramCmd = Get-Command engram -ErrorAction SilentlyContinue
if ($engramCmd) {
    try {
        Invoke-EngramCommandWithProgress `
            -Executable $engramCmd.Source `
            -Subcommand "sync" `
            -GlobalArguments @("--timeout", "300") `
            -Arguments @("--direct") `
            -Activity "Synchronizing Engram index" `
            -Status "Direct pre-warm before Copilot startup"
    } catch {
        Write-Warning "engram direct pre-warm failed; retrying via daemon sync: $_"
        try {
            & $engramCmd.Source --format text bind
            Invoke-EngramCommandWithProgress `
                -Executable $engramCmd.Source `
                -Subcommand "sync" `
                -GlobalArguments @("--timeout", "300") `
                -Activity "Synchronizing Engram index" `
                -Status "Daemon-backed pre-warm fallback"
        } catch {
            Write-Warning "engram sync failed (non-fatal): $_"
        }
    }
}

$copilotArguments = @()
if (-not ($args -contains "--remote")) {
    $copilotArguments += "--remote"
}
$copilotArguments += $args

& $copilotExe @copilotArguments

# ── Claude Code ─────────────────────────────────────────────────────────────
# Uncomment to run Claude Code with workspace-local state directories.
# CLAUDE_CONFIG_DIR redirects Claude's config and history to the workspace.
# Verify that your installed version of Claude Code supports this env variable.
#
# $env:CLAUDE_CONFIG_DIR = ".\.claude"
# claude

# ── OpenAI Codex / Agents ────────────────────────────────────────────────────
# Uncomment to run Codex with a workspace-local API key file.
#
# $env:OPENAI_API_KEY = (Get-Content .openai-token -Raw).Trim()
# codex
