//! MCP client configuration generation.
//!
//! Generates editor-specific MCP client configuration files that point
//! to the installed `graphtor-docs` binary for VS Code, Cursor, and
//! GitHub Copilot CLI. All generated paths are relative to the project
//! root.

use std::fs;
use std::path::Path;

use graphtor_core::GraphtorError;

/// A supported MCP client editor target.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Editor {
    /// VS Code — writes `.vscode/mcp.json`.
    VsCode,
    /// Cursor — writes `.cursor/mcp.json`.
    Cursor,
    /// GitHub Copilot CLI — writes `.github/copilot/mcp.json`.
    Copilot,
}

impl Editor {
    /// Parse an editor name from a command-line string (case-insensitive).
    pub fn from_str(s: &str) -> Option<Self> {
        match s.to_lowercase().as_str() {
            "vscode" | "vs-code" | "code" => Some(Self::VsCode),
            "cursor" => Some(Self::Cursor),
            "copilot" | "github-copilot" => Some(Self::Copilot),
            _ => None,
        }
    }

    /// Return the config file path relative to the project root.
    fn config_path(&self) -> &'static str {
        match self {
            Self::VsCode => ".vscode/mcp.json",
            Self::Cursor => ".cursor/mcp.json",
            Self::Copilot => ".github/copilot/mcp.json",
        }
    }
}

/// Generate MCP client config files for the given editors.
///
/// For each editor, creates the parent directory if needed and writes
/// a JSON config that registers `graphtor-docs` as an MCP server. If
/// the config file already exists it is left unchanged (idempotent).
///
/// Pass an empty `editors` slice to generate configs for all supported
/// editors.
///
/// # Errors
///
/// Returns [`GraphtorError::Config`] on I/O failure.
pub fn generate_mcp_configs(
    project_root: &Path,
    editors: &[Editor],
) -> Result<Vec<String>, GraphtorError> {
    let all_editors = [Editor::VsCode, Editor::Cursor, Editor::Copilot];
    let targets: &[Editor] = if editors.is_empty() {
        &all_editors
    } else {
        editors
    };

    let binary_path = format!(".graphtor/bin/graphtor-docs{}", binary_ext());
    let mut written: Vec<String> = Vec::new();

    for editor in targets {
        let rel_path = editor.config_path();
        let dest = project_root.join(rel_path);

        if dest.exists() {
            // Already configured; skip.
            continue;
        }

        if let Some(parent) = dest.parent() {
            fs::create_dir_all(parent).map_err(|e| GraphtorError::Config {
                message: format!("failed to create {}: {e}", parent.display()),
                field: None,
            })?;
        }

        let config = mcp_config_json(&binary_path);
        fs::write(&dest, config).map_err(|e| GraphtorError::Config {
            message: format!("failed to write {rel_path}: {e}"),
            field: None,
        })?;

        written.push(rel_path.to_string());
    }

    Ok(written)
}

/// Remove MCP client config files generated by graphtor-docs.
///
/// Only removes files that contain the graphtor-docs managed marker.
///
/// # Errors
///
/// Returns [`GraphtorError::Config`] on I/O failure.
pub fn remove_mcp_configs(
    project_root: &Path,
    editors: &[Editor],
) -> Result<Vec<String>, GraphtorError> {
    let all_editors = [Editor::VsCode, Editor::Cursor, Editor::Copilot];
    let targets: &[Editor] = if editors.is_empty() {
        &all_editors
    } else {
        editors
    };

    let mut removed: Vec<String> = Vec::new();
    for editor in targets {
        let rel_path = editor.config_path();
        let dest = project_root.join(rel_path);
        if !dest.exists() {
            continue;
        }
        let content = fs::read_to_string(&dest).unwrap_or_default();
        if content.contains("graphtor-docs") {
            fs::remove_file(&dest).map_err(|e| GraphtorError::Config {
                message: format!("failed to remove {rel_path}: {e}"),
                field: None,
            })?;
            removed.push(rel_path.to_string());
        }
    }
    Ok(removed)
}

/// Return platform-specific binary extension (`.exe` on Windows, empty elsewhere).
fn binary_ext() -> &'static str {
    if cfg!(windows) {
        ".exe"
    } else {
        ""
    }
}

/// Render the MCP client JSON config for the given binary path.
fn mcp_config_json(binary_path: &str) -> String {
    // Standard MCP server registration format understood by VS Code, Cursor,
    // and GitHub Copilot CLI.
    format!(
        r#"{{
  "mcpServers": {{
    "graphtor-docs": {{
      "command": "{binary_path}",
      "args": ["serve"],
      "transport": "stdio"
    }}
  }}
}}
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_creates_files() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let written = generate_mcp_configs(tmp.path(), &[Editor::VsCode]).expect("generate");
        assert_eq!(written.len(), 1);
        let content = fs::read_to_string(tmp.path().join(".vscode/mcp.json")).expect("read");
        assert!(content.contains("graphtor-docs"));
    }

    #[test]
    fn generate_is_idempotent() {
        let tmp = tempfile::tempdir().expect("tempdir");
        generate_mcp_configs(tmp.path(), &[Editor::VsCode]).expect("first");
        let second = generate_mcp_configs(tmp.path(), &[Editor::VsCode]).expect("second");
        assert!(second.is_empty(), "second run should produce no writes");
    }
}
