//! MCP client configuration generation.
//!
//! Generates a single workspace-root `.mcp.json` configuration file that
//! registers the installed `graphtor-docs` binary as an MCP server. This is
//! the editor-agnostic standard understood by MCP clients; graphtor-docs no
//! longer writes editor-specific config files. Uninstall also removes legacy
//! editor-specific config paths (`.vscode/mcp.json`, `.cursor/mcp.json`,
//! `.github/copilot/mcp.json`) when they contain the `graphtor-docs` marker.

use std::fs;
use std::io::ErrorKind;
use std::path::Path;

use graphtor_core::GraphtorError;

/// Workspace-root MCP client config path (the current standard).
const MCP_CONFIG_PATH: &str = ".mcp.json";

/// Legacy editor-specific config paths cleaned up on uninstall.
const LEGACY_CONFIG_PATHS: &[&str] = &[
    ".vscode/mcp.json",
    ".cursor/mcp.json",
    ".github/copilot/mcp.json",
];

/// Managed marker identifying graphtor-docs-generated config files.
const GRAPHTOR_MARKER: &str = "graphtor-docs";

/// Generate the workspace-root `.mcp.json` MCP client config.
///
/// Writes a `.mcp.json` file at the project root that registers
/// `graphtor-docs` as an MCP server. If the config file already exists it is
/// left unchanged (idempotent). Returns the relative paths written — empty
/// when the file already existed.
///
/// # Errors
///
/// Returns [`GraphtorError::Config`] on I/O failure.
pub fn generate_mcp_config(project_root: &Path) -> Result<Vec<String>, GraphtorError> {
    let dest = project_root.join(MCP_CONFIG_PATH);

    if dest.exists() {
        // Already configured; leave it unchanged.
        return Ok(Vec::new());
    }

    if let Some(parent) = dest.parent() {
        fs::create_dir_all(parent).map_err(|e| GraphtorError::Config {
            message: format!("failed to create {}: {e}", parent.display()),
            field: None,
        })?;
    }

    let binary_path = format!(".graphtor/bin/graphtor-docs{}", binary_ext());
    let config = mcp_config_json(&binary_path);
    fs::write(&dest, config).map_err(|e| GraphtorError::Config {
        message: format!("failed to write {MCP_CONFIG_PATH}: {e}"),
        field: None,
    })?;

    Ok(vec![MCP_CONFIG_PATH.to_string()])
}

/// Remove MCP client config files generated by graphtor-docs.
///
/// Removes the workspace-root `.mcp.json` and any legacy editor-specific
/// config files (`.vscode/mcp.json`, `.cursor/mcp.json`,
/// `.github/copilot/mcp.json`) that contain the graphtor-docs managed marker.
///
/// # Errors
///
/// Returns [`GraphtorError::Config`] on I/O failure.
pub fn remove_mcp_config(project_root: &Path) -> Result<Vec<String>, GraphtorError> {
    let mut removed: Vec<String> = Vec::new();
    for rel_path in std::iter::once(MCP_CONFIG_PATH).chain(LEGACY_CONFIG_PATHS.iter().copied()) {
        let dest = project_root.join(rel_path);
        let content = match fs::read_to_string(&dest) {
            Ok(s) => s,
            Err(e) if e.kind() == ErrorKind::NotFound => continue,
            Err(e) => {
                return Err(GraphtorError::Config {
                    message: format!("failed to read {rel_path}: {e}"),
                    field: None,
                })
            }
        };
        if content.contains(GRAPHTOR_MARKER) {
            fs::remove_file(&dest).map_err(|e| GraphtorError::Config {
                message: format!("failed to remove {rel_path}: {e}"),
                field: None,
            })?;
            removed.push(rel_path.to_string());
        }
    }
    Ok(removed)
}

/// Return platform-specific binary extension (`.exe` on Windows, empty elsewhere).
fn binary_ext() -> &'static str {
    if cfg!(windows) {
        ".exe"
    } else {
        ""
    }
}

/// Render the MCP client JSON config for the given binary path.
fn mcp_config_json(binary_path: &str) -> String {
    // Standard MCP server registration format understood by VS Code and Cursor.
    format!(
        r#"{{
  "mcpServers": {{
    "graphtor-docs": {{
      "command": "{binary_path}",
      "args": ["serve"],
      "transport": "stdio"
    }}
  }}
}}
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_creates_root_mcp_json() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let written = generate_mcp_config(tmp.path()).expect("generate");
        assert_eq!(written, vec![".mcp.json".to_string()]);
        let content = fs::read_to_string(tmp.path().join(".mcp.json")).expect("read");
        assert!(content.contains("graphtor-docs"));
    }

    #[test]
    fn generate_is_idempotent() {
        let tmp = tempfile::tempdir().expect("tempdir");
        generate_mcp_config(tmp.path()).expect("first");
        let second = generate_mcp_config(tmp.path()).expect("second");
        assert!(second.is_empty(), "second run should produce no writes");
    }

    #[test]
    fn generate_does_not_write_editor_configs() {
        let tmp = tempfile::tempdir().expect("tempdir");
        generate_mcp_config(tmp.path()).expect("generate");
        assert!(!tmp.path().join(".vscode/mcp.json").exists());
        assert!(!tmp.path().join(".cursor/mcp.json").exists());
        assert!(!tmp.path().join(".github/copilot/mcp.json").exists());
    }

    #[test]
    fn remove_removes_root_mcp_json() {
        let tmp = tempfile::tempdir().expect("tempdir");
        generate_mcp_config(tmp.path()).expect("generate");
        let removed = remove_mcp_config(tmp.path()).expect("remove");
        assert_eq!(removed, vec![".mcp.json".to_string()]);
        assert!(!tmp.path().join(".mcp.json").exists());
    }

    #[test]
    fn remove_removes_legacy_editor_configs() {
        let tmp = tempfile::tempdir().expect("tempdir");
        for legacy in [
            ".vscode/mcp.json",
            ".cursor/mcp.json",
            ".github/copilot/mcp.json",
        ] {
            let path = tmp.path().join(legacy);
            fs::create_dir_all(path.parent().expect("parent")).expect("mkdir");
            fs::write(&path, mcp_config_json(".graphtor/bin/graphtor-docs")).expect("write");
        }

        let removed = remove_mcp_config(tmp.path()).expect("remove");

        assert_eq!(
            removed,
            vec![
                ".vscode/mcp.json".to_string(),
                ".cursor/mcp.json".to_string(),
                ".github/copilot/mcp.json".to_string(),
            ]
        );
        assert!(!tmp.path().join(".vscode/mcp.json").exists());
        assert!(!tmp.path().join(".cursor/mcp.json").exists());
        assert!(!tmp.path().join(".github/copilot/mcp.json").exists());
    }

    #[test]
    fn remove_ignores_unmanaged_files() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let path = tmp.path().join(".mcp.json");
        fs::write(&path, "{\"mcpServers\": {}}").expect("write");
        let removed = remove_mcp_config(tmp.path()).expect("remove");
        assert!(removed.is_empty(), "unmanaged file should be left in place");
        assert!(path.exists());
    }
}
