@echo off
REM Run all group clone scripts sequentially.
REM Edit this file to comment out groups you don't need.

call "%~dp0clone-01-azure-core-and-cli.bat"
call "%~dp0clone-02-azure-architecture-and-best-practices.bat"
call "%~dp0clone-03-azure-ai-and-machine-learning.bat"
call "%~dp0clone-04-azure-compute-and-infrastructure.bat"
call "%~dp0clone-05-azure-databases-and-analytics.bat"
call "%~dp0clone-06-azure-storage.bat"
call "%~dp0clone-07-azure-networking.bat"
call "%~dp0clone-08-azure-security-and-compliance.bat"
REM call "%~dp0clone-09-microsoft-identity-platform.bat"
call "%~dp0clone-10-azure-devops-and-ci-cd.bat"
REM call "%~dp0clone-11-azure-monitoring-and-management.bat"
REM call "%~dp0clone-12-azure-iot-and-edge.bat"
call "%~dp0clone-13-azure-stack.bat"
::call "%~dp0clone-14-enterprise-mobility-and-endpoint-management.bat"
::call "%~dp0clone-15-biztalk-sql-server-and-data-platform.bat"
::call "%~dp0clone-16-microsoft-365-and-office.bat"
REM call "%~dp0clone-17-microsoft-teams-and-communication.bat"
REM call "%~dp0clone-18-microsoft-graph.bat"
REM call "%~dp0clone-19-microsoft-copilot-and-ai-assistants.bat"
::call "%~dp0clone-20-bot-framework-and-conversational-ai.bat"
::call "%~dp0clone-21-gaming-media-and-mixed-reality.bat"
::call "%~dp0clone-22-windows-development.bat"
::call "%~dp0clone-23-windows-server-and-iis.bat"
call "%~dp0clone-24-powershell.bat"
REM call "%~dp0clone-25-visual-studio-and-developer-tools.bat"
call "%~dp0clone-26-net-candand-and-language-ecosystem.bat"
REM call "%~dp0clone-27-mobile-development.bat"
::call "%~dp0clone-28-dynamics-365.bat"
REM call "%~dp0clone-29-power-platform.bat"
call "%~dp0clone-30-microsoft-fabric-and-analytics.bat"
REM call "%~dp0clone-31-azure-sdk-language-references.bat"
REM call "%~dp0clone-32-quantum-computing.bat"
::call "%~dp0clone-33-bing-maps-and-advertising.bat"
::call "%~dp0clone-34-partner-and-programs.bat"
REM call "%~dp0clone-35-open-standards-and-apis.bat"
REM call "%~dp0clone-36-migration-tools.bat"
REM call "%~dp0clone-37-community-and-learning.bat"
::call "%~dp0clone-38-documentation-infrastructure-and-style.bat"

echo.
echo All groups complete.
