# pre-commit-pipeline-topology.ps1
# Generated by autoharness | Template: pre-commit-pipeline-topology.ps1.tmpl
#
# Pre-commit hook: runs the deterministic `autoharness gate pipeline-topology`
# ambient check before a commit. This is the commit-time half of the P-001
# (at-most-one-active-shipment) / P-016 (single implementation worktree)
# local-gating pair; `pre-push-quality-gates.ps1` (B1) covers the push-time
# invocation.
#
# NON-SHIPMENT-SCOPED INVOCATION: no human-supplied --shipment is passed. The
# gate deterministically resolves its target (the currently-claimed active
# shipment from backlogit, or the current branch slug) and always runs
# `--phase ambient` here (at-most-one-active, validating the resolved target
# when one exists). No resolvable claimed shipment / zero active shipments ->
# gate verdict PASS (existence-guarded, so ordinary commits with no claimed
# shipment are unaffected); a mismatched single active or two-or-more-active
# shipments produces a fail-closed gate verdict of BLOCK.
#
# GATE VERDICT vs. HOOK ENFORCEMENT are two separate things. The verdict above
# describes what `autoharness gate pipeline-topology` decides. Whether THIS
# HOOK propagates a BLOCK verdict into a non-zero exit is controlled solely by
# the advisory toggle below: by default the hook warns and exits 0 even on
# BLOCK, and it fails the commit only when
# $env:AUTOHARNESS_TOPOLOGY_GATE_BLOCKING is 'true'. Local commit-time
# enforcement is therefore opt-in; the authoritative P-001 / P-016 enforcement
# point is the agent workflow and CI, not this hook.
#
# Behavior:
#   * Absent 'autoharness' -> warn+skip, never a hard failure.
#   * Advisory-first by default (staged rollout): a gate failure warns but
#     does NOT block the commit unless $env:AUTOHARNESS_TOPOLOGY_GATE_BLOCKING
#     is 'true'.
#   * Single deterministic pass — no retry loop.
#
# Install (opt-in — the harness never silently overwrites your .git/hooks):
#   Git invokes the hook by the exact name `pre-commit` (no extension) and
#   runs it with a POSIX shell — not PowerShell. So this .ps1 cannot be git's
#   hook directly; register a POSIX `pre-commit` that execs it:
#     * .git/hooks/pre-commit (or <hooks-dir>/pre-commit) containing:
#         #!/bin/sh
#         exec pwsh -NoProfile -File "$(dirname "$0")/pre-commit-pipeline-topology.ps1" "$@"
#       then, for a dedicated directory:
#         git config core.hooksPath <hooks-dir>
#   If another pre-commit check (e.g. pre-commit-markdownlint.ps1) already
#   occupies `pre-commit`, chain both from a single dispatcher rather than
#   overwriting one with the other.
#   To bypass once: git commit --no-verify

$ErrorActionPreference = 'Continue'

# Run from repo root so repo-root-relative gate invocation is valid.
$RepoRoot = & git rev-parse --show-toplevel
Set-Location $RepoRoot

if (-not (Get-Command autoharness -ErrorAction SilentlyContinue)) {
    Write-Warning "'autoharness' not found — skipping pipeline-topology gate."
    exit 0
}

Write-Host "[Pipeline-Topology] autoharness gate pipeline-topology --mode manual --phase ambient"
autoharness gate pipeline-topology --mode manual --phase ambient
if ($LASTEXITCODE -ne 0) {
    if ($env:AUTOHARNESS_TOPOLOGY_GATE_BLOCKING -eq 'true') {
        Write-Error "pipeline-topology gate failed — commit blocked (P-001/P-016)."
        exit 1
    }
    Write-Warning "pipeline-topology gate failed (advisory) — commit not blocked."
    Write-Warning "  Set `$env:AUTOHARNESS_TOPOLOGY_GATE_BLOCKING = 'true' to enforce, or commit --no-verify to bypass entirely."
}

exit 0
